import {
  assertEquals,
} from "https://deno.land/std/testing/asserts.ts";
import extractSets from "./extractSets.ts";

Deno.test("should convert valid match to sets", async () => {
  const sets = extractSets({
    players: ["One", "Two"],
    scores: [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      0,
      0,
      0,
      0,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
    ],
  });

  assertEquals(
    sets,
    [
      {
        "winner": "One",
        "setScore": { "One": 6, "Two": 5 },
        "gameLog": [
          {
            "gameWinner": "One",
            "currentScore": { "One": 1 },
            winner: undefined,
          },
          {
            "gameWinner": "One",
            "currentScore": { "One": 2 },
            winner: undefined,
          },
          {
            "gameWinner": "One",
            "currentScore": { "One": 3 },
            winner: undefined,
          },
          {
            "gameWinner": "One",
            "currentScore": { "One": 4 },
            winner: undefined,
          },
          {
            "gameWinner": "One",
            "currentScore": { "One": 5 },
            winner: undefined,
          },
          {
            "gameWinner": "Two",
            "currentScore": { "One": 5, "Two": 1 },
            winner: undefined,
          },
          {
            "gameWinner": "Two",
            "currentScore": { "One": 5, "Two": 2 },
            winner: undefined,
          },
          {
            "gameWinner": "Two",
            "currentScore": { "One": 5, "Two": 3 },
            winner: undefined,
          },
          {
            "gameWinner": "Two",
            "currentScore": { "One": 5, "Two": 4 },
            winner: undefined,
          },
          {
            "gameWinner": "Two",
            "currentScore": { "One": 5, "Two": 5 },
            winner: undefined,
          },
          {
            "gameWinner": "One",
            "currentScore": { "One": 6, "Two": 5 },
            "winner": "One",
          },
        ],
      },
      {
        "winner": "Two",
        "setScore": { "Two": 6 },
        "gameLog": [
          {
            "gameWinner": "Two",
            "currentScore": { "Two": 1 },
            winner: undefined,
          },
          {
            "gameWinner": "Two",
            "currentScore": { "Two": 2 },
            winner: undefined,
          },
          {
            "gameWinner": "Two",
            "currentScore": { "Two": 3 },
            winner: undefined,
          },
          {
            "gameWinner": "Two",
            "currentScore": { "Two": 4 },
            winner: undefined,
          },
          {
            "gameWinner": "Two",
            "currentScore": { "Two": 5 },
            winner: undefined,
          },
          {
            "gameWinner": "Two",
            "currentScore": { "Two": 6 },
            "winner": "Two",
          },
        ],
      },
      {
        "winner": "Two",
        "setScore": { "One": 5, "Two": 6 },
        "gameLog": [
          {
            "gameWinner": "One",
            "currentScore": { "One": 1 },
            winner: undefined,
          },
          {
            "gameWinner": "One",
            "currentScore": { "One": 2 },
            winner: undefined,
          },
          {
            "gameWinner": "One",
            "currentScore": { "One": 3 },
            winner: undefined,
          },
          {
            "gameWinner": "One",
            "currentScore": { "One": 4 },
            winner: undefined,
          },
          {
            "gameWinner": "One",
            "currentScore": { "One": 5 },
            winner: undefined,
          },
          {
            "gameWinner": "Two",
            "currentScore": { "One": 5, "Two": 1 },
            winner: undefined,
          },
          {
            "gameWinner": "Two",
            "currentScore": { "One": 5, "Two": 2 },
            winner: undefined,
          },
          {
            "gameWinner": "Two",
            "currentScore": { "One": 5, "Two": 3 },
            winner: undefined,
          },
          {
            "gameWinner": "Two",
            "currentScore": { "One": 5, "Two": 4 },
            winner: undefined,
          },
          {
            "gameWinner": "Two",
            "currentScore": { "One": 5, "Two": 5 },
            winner: undefined,
          },
          {
            "gameWinner": "Two",
            "currentScore": { "One": 5, "Two": 6 },
            "winner": "Two",
          },
        ],
      },
    ],
  );
});
